### ISSUE TITLE
Compilation error in Ubuntu 18.04

### ISSUE THREAD

**Issue by gammell** [pdfpc/pdfpc#589]
The current master branch doesn't compile in Ubuntu 18.04 unless `-DREST=OFF` is set in cmake. I have both `libsoup2.4-dev` and `libsoup2.4-1` installed (and all other dependencies listed in  the README).

Apologies if you're already aware, just trying to help out by reporting it.

The problem appears to be this line:
https://github.com/pdfpc/pdfpc/blob/378a6a25487c5cbc1796cedc560fc3f88a2fb10b/src/classes/rest_server.vala#L513

```
$ cmake ../
[...]
$ make
[  3%] Generating classes/action/action_mapping.c, classes/action/link_action.c, classes/action/movie.c, classes/config_file_reader.c, classes/dbus_server.c, classes/drawings/drawing.c, classes/drawings/storage.c, classes/metadata/pdf.c, classes/metadata/xml.c, classes/options.c, classes/presentation_controller.c, classes/renderer/cache.c, classes/renderer/markdown.c, classes/renderer/pdf.c, classes/rest_server.c, classes/timer_label.c, classes/view/behaviour/base.c, classes/view/behaviour/pdf_link.c, classes/view/markdown.c, classes/view/pdf.c, classes/view/transition_manager.c, classes/view/video.c, classes/window/fullscreen.c, classes/window/overview.c, classes/window/presentation.c, classes/window/presenter.c, classes/window/qrcode.c, interfaces/controllable.c, pdfpc.c
/opt/pdfpc/git/src/classes/rest_server.vala:513.13-513.34: warning: Access to static member `Soup.AuthDomainBasic.set_auth_callback' with an instance reference
            auth.set_auth_callback((domain, msg, username, password) => {
            ^^^^^^^^^^^^^^^^^^^^^^
/opt/pdfpc/git/src/classes/rest_server.vala:513.36-522.17: error: Cannot convert lambda expression to `Soup.AuthDomain'
/opt/pdfpc/git/src/classes/rest_server.vala:513.13-522.18: error: 1 missing arguments for `void Soup.AuthDomainBasic.set_auth_callback (Soup.AuthDomain, owned Soup.AuthDomainBasicAuthCallback)'
Compilation failed: 2 error(s), 1 warning(s)
src/CMakeFiles/pdfpc.dir/build.make:112: recipe for target 'src/classes/action/action_mapping.c' failed
make[2]: *** [src/classes/action/action_mapping.c] Error 1
CMakeFiles/Makefile2:196: recipe for target 'src/CMakeFiles/pdfpc.dir/all' failed
make[1]: *** [src/CMakeFiles/pdfpc.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by fnevgeny** [comment]
Very strange... Not sure what's confusing vala here.

**Comment by gammell** [comment]
Let me know if I can provide any additional info to help out, I really appreciate pdfpc.

**Comment by fnevgeny** [comment]
```
# apt-file search libsoup-2.4.vapi
libsoup2.4-dev: /usr/share/vala/vapi/libsoup-2.4.vapi
valac-0.40-vapi: /usr/share/vala-0.40/vapi/libsoup-2.4.vapi
```
That's the problem. Remove/rename `/usr/share/vala/vapi/libsoup-2.4.vapi`, and the pdfpc compilation should succeed.

> Let me know if I can provide any additional info to help out,

If you don't mind, please file a bug with Ubuntu (though this stems from Debian, of course). It's not specific to 18.04, but in 20.04 the two files are nearly identical and don't cause an issue.

**Comment by gammell** [comment]
Sure, I can try and do that next week. Can you help me understand the problem? Is it that both `libsoup2.4-dev` and `valac-0.40-vapi` provide `libsoup-2.4.vapi` (to different locations) and that the one provided by `libsoup2.4-dev` is incorrect or something?

**Comment by fnevgeny** [comment]
Yes, there must be only one. The libsoup2.4-dev's version is outdated.

**Comment by gammell** [comment]
Bug reported to Ubuntu here:
https://bugs.launchpad.net/ubuntu/+source/libsoup2.4/+bug/1921078

**Comment by fnevgeny** [comment]
Thanks!
