### ISSUE TITLE
Fix build with vala 0.52+ due to API change in gstreamer

### ISSUE THREAD

**Issue by cho-m** [pdfpc/pdfpc#594]
**Expected Behaviour**
Successfully compile `pdfpc` with latest `vala 0.52.3`.

**Actual Behaviour**
Compilation fails due to API change. Error from Homebrew CI run:
```make
/tmp/pdfpc-20210504-85231-1xrsgz4/pdfpc-4.4.1/src/classes/action/movie.vala:551.13-551.26: error: The name `from_caps' does not exist in the context of `Gst.Video.Info' (gstreamer-video-1.0)
            info.from_caps(caps);
            ^^^^^^^^^^^^^^
Compilation failed: 1 error(s), 0 warning(s)
make[2]: *** [src/classes/action/action_mapping.c] Error 1
make[1]: *** [src/CMakeFiles/pdfpc.dir/all] Error 2
make: *** [all] Error 2
```

**Steps to reproduce**
Compile `pdfpc` from source with latest `vala`.

pdfpc version: **4.4.1 (Homebrew build)**
Used Distribution (GTK version, vala version): **Homebrew's `gtk+3` (3.24.29), `vala` (0.52.3)**
Display Server (X/Wayland):
HiDPI Setting (yes/no):

I believe issue still exists in `master` branch:
https://github.com/pdfpc/pdfpc/blob/d7677723a7aa384243ed609e88e56f659045b4ac/src/classes/action/movie.vala#L556-L557

---

Related API change from VALA 0.50.8 to 0.52.3 `vapi/gstreamer-video-1.0.vapi`:
```diff
@@ -361,8 +361,6 @@ namespace Gst {
 			public Gst.Video.Info copy ();
 			[Version (since = "1.6")]
 			public void free ();
-			public bool from_caps (Gst.Caps caps);
-			public void init ();
 			public bool is_equal (Gst.Video.Info other);
 			public bool set_format (Gst.Video.Format format, uint width, uint height);
 			[Version (since = "1.16")]
@@ -1926,6 +1931,10 @@ namespace Gst {
 		[Version (since = "1.20")]
 		public static bool hdr_parse_hdr10_plus (uint8 data, size_t size, out Gst.Video.HDR10Plus hdr10_plus);
 		[CCode (cheader_filename = "gst/video/video.h")]
+		public static bool info_from_caps (out unowned Gst.Video.Info info, Gst.Caps caps);
+		[CCode (cheader_filename = "gst/video/video.h")]
+		public static void info_init (out unowned Gst.Video.Info info);
+		[CCode (cheader_filename = "gst/video/video.h")]
 		[Version (since = "1.6")]
 		public static Gst.Video.InterlaceMode interlace_mode_from_string (string mode);
 		[CCode (cheader_filename = "gst/video/video.h")]
```

**Comment by cho-m** [comment]
One possibility to support <=0.50 and 0.52+ could be using preprocessor: https://wiki.gnome.org/Projects/Vala/Manual/Preprocessor#Built-in_defines 

e.g. `VALA_X_Y` --> `#if VALA_0_52`

**Comment by sanjayankur31** [comment]
We're also seeing this build failure in Fedora rawhide now. 

https://kojipkgs.fedoraproject.org//work/tasks/3045/72443045/build.log

**Comment by fnevgeny** [comment]
> **EDIT:** Needs something more in fix...

@cho-m What else is missing?

**Comment by cho-m** [comment]
@fnevgeny Sorry, I haven't had the chance to figure it out.

It compiled fine when I first wrote the comment.
However, I tried testing on the Apollo example and it didn't work correctly, so I added EDIT comment.

**Comment by fnevgeny** [comment]
I see. Vala folks got it wrong, I believe. No idea why they changed the API. You can drop `out unowned` from the respective definition in `gstreamer-video-1.0.vapi`. The pdfpc code should be changed to
```vala
            var info = new Gst.Video.Info();
#if VALA_0_52
            Gst.Video.info_from_caps(info, caps);
#else
            info.from_caps(caps);
#endif
```
But this is really a VAPI bug.

**Comment by fnevgeny** [comment]
Upstream report: https://gitlab.gnome.org/GNOME/vala/-/issues/1210

**Comment by fnevgeny** [comment]
Proper fixes from the Vala project (for both 0.52 and future 0.54) are now available. Closing the ticket.
