### ISSUE TITLE
Error building 4.0.7 on Fedora rawhide

### ISSUE THREAD

**Issue by sanjayankur31** [pdfpc/pdfpc#249]
Hi! I was updating the package in Fedora but it failed to build on rawhide. I'm not entirely sure, but it looks like a code issue:

```
+ /usr/bin/cmake -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON -DSYSCONFDIR=/etc .
-- The C compiler identification is GNU 7.1.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Vala: /usr/bin/valac (found suitable version "0.36.3", minimum required is "0.26") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.3.7") 
-- Checking for module 'gobject-2.0'
--   Found gobject-2.0, version 2.53.3
-- Checking for module 'gio-2.0'
--   Found gio-2.0, version 2.53.3
-- Checking for module 'gee-0.8'
--   Found gee-0.8, version 0.20.0
-- Checking for module 'poppler-glib'
--   Found poppler-glib, version 0.56.0
-- Checking for module 'gtk+-3.0>=3.10'
--   Found gtk+-3.0, version 3.22.16
-- Checking for module 'gthread-2.0'
--   Found gthread-2.0, version 2.53.3
-- Checking for module 'pangocairo'
--   Found pangocairo, version 1.40.6
-- Checking for module 'gstreamer-1.0'
--   Found gstreamer-1.0, version 1.12.1
-- Checking for module 'gstreamer-base-1.0'
--   Found gstreamer-base-1.0, version 1.12.1
-- Checking for module 'gstreamer-audio-1.0'
--   Found gstreamer-audio-1.0, version 1.12.1
-- Checking for module 'gstreamer-video-1.0'
--   Found gstreamer-video-1.0, version 1.12.1
-- Checking for module 'gdk-x11-3.0'
--   Found gdk-x11-3.0, version 3.22.16
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:
    CMAKE_CXX_FLAGS_RELEASE
    CMAKE_C_FLAGS_RELEASE
    CMAKE_Fortran_FLAGS_RELEASE
    INCLUDE_INSTALL_DIR
    LIB_INSTALL_DIR
    LIB_SUFFIX
    SHARE_INSTALL_PREFIX
    SYSCONF_INSTALL_DIR
-- Build files have been written to: /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc
+ make -j48
/usr/bin/cmake -H/builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc -B/builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/CMakeFiles /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc'
make -f src/CMakeFiles/pdfpc.dir/build.make src/CMakeFiles/pdfpc.dir/depend
make[2]: Entering directory '/builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc'
[  3%] Generating classes/action/action_mapping.c, classes/action/link_action.c, classes/action/movie.c, classes/cache_status.c, classes/config_file_reader.c, classes/dbus_server.c, classes/metadata/pdf.c, classes/metadata/slides_notes.c, classes/options.c, classes/presentation_controller.c, classes/renderer/cache/base.c, classes/renderer/cache/png/engine.c, classes/renderer/cache/png/item.c, classes/renderer/cache/png/persistent/engine.c, classes/renderer/cache/simple/engine.c, classes/renderer/pdf.c, classes/scaler.c, classes/timer_label.c, classes/view/behaviour/base.c, classes/view/behaviour/pdf_link.c, classes/view/pdf.c, classes/window/fullscreen.c, classes/window/overview.c, classes/window/presentation.c, classes/window/presenter.c, interfaces/controllable.c, paths.c, pdfpc.c, presenter.vapi, presenter.h, presenter_internal.h
cd /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src && /usr/bin/valac -C --header=/builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/presenter.h --internal-header=/builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/presenter_internal.h --vapi=presenter.vapi -b /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src -d /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src --pkg=gio-2.0 --pkg=gee-0.8 --pkg=poppler-glib --pkg=gtk+-3.0 --pkg=pangocairo --pkg=posix --pkg=gstreamer-1.0 --pkg=gstreamer-base-1.0 --pkg=gstreamer-audio-1.0 --pkg=gstreamer-video-1.0 --pkg=gdk-x11-3.0 --thread --debug --enable-experimental -D MOVIES /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/action/action_mapping.vala /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/action/link_action.vala /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/action/movie.vala /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/cache_status.vala /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/config_file_reader.vala /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/dbus_server.vala /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/metadata/pdf.vala /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/metadata/slides_notes.vala /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/options.vala /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/presentation_controller.vala /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/renderer/cache/base.vala /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/renderer/cache/png/engine.vala /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/renderer/cache/png/item.vala /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/renderer/cache/png/persistent/engine.vala /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/renderer/cache/simple/engine.vala /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/renderer/pdf.vala /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/scaler.vala /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/timer_label.vala /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/view/behaviour/base.vala /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/view/behaviour/pdf_link.vala /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/view/pdf.vala /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/window/fullscreen.vala /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/window/overview.vala /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/window/presentation.vala /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/window/presenter.vala /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/interfaces/controllable.vala /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/paths.vala /builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/pdfpc.vala
/builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/window/fullscreen.vala:87.17-87.55: warning: Gdk.Screen.get_monitor_geometry has been deprecated since 3.22
/builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/window/fullscreen.vala:90.31-90.74: warning: Gdk.Display.get_device_manager has been deprecated since 3.20.
/builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/window/fullscreen.vala:90.31-90.95: warning: Gdk.DeviceManager.get_client_pointer has been deprecated since 3.20
/builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/window/fullscreen.vala:94.42-94.80: warning: Gdk.Screen.get_monitor_at_point has been deprecated since 3.22
/builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/window/fullscreen.vala:95.17-95.55: warning: Gdk.Screen.get_monitor_geometry has been deprecated since 3.22
/builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/window/fullscreen.vala:98.30-98.72: warning: Gdk.Screen.get_monitor_scale_factor has been deprecated since 3.22
/builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/window/overview.vala:302.32-302.35: error: Argument 1: Cannot pass value to reference or output parameter
            this.slides.remove(iter);
                               ^^^^
/builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/window/presenter.vala:579.13-579.41: warning: Gtk.Widget.override_font has been deprecated since 3.16
/builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/window/presenter.vala:591.13-591.41: warning: Gtk.Widget.override_font has been deprecated since 3.16
/builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/window/presenter.vala:223.17-223.45: warning: Gtk.Widget.override_font has been deprecated since 3.16
/builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/presentation_controller.vala:329.13-329.60: warning: Gtk.Widget.override_background_color has been deprecated since 3.16
/builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/classes/presentation_controller.vala:315.13-315.63: warning: Gtk.Widget.override_background_color has been deprecated since 3.16
/builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/pdfpc.vala:262.64-262.84: warning: Gdk.Screen.get_n_monitors has been deprecated since 3.22
/builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/pdfpc.vala:265.41-265.66: warning: Gdk.Screen.get_primary_monitor has been deprecated since 3.22
/builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/src/pdfpc.vala:267.42-267.67: warning: Gdk.Screen.get_primary_monitor has been deprecated since 3.22
Compilation failed: 1 error(s), 14 warning(s)
make[2]: *** [src/CMakeFiles/pdfpc.dir/build.make:92: src/classes/action/action_mapping.c] Error 1
make[2]: Leaving directory '/builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc'
make[1]: Leaving directory '/builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc'
make[1]: *** [CMakeFiles/Makefile2:121: src/CMakeFiles/pdfpc.dir/all] Error 2
make: *** [Makefile:133: all] Error 2
```

The full log is attached too - [pdfpc-rawhide-build.txt](https://github.com/pdfpc/pdfpc/files/1124907/pdfpc-rawhide-build.txt).

**Comment by AndreasBilke** [comment]
Are you sure that you that you are using v4.0.7? In your build path `/builddir/build/BUILD/pdfpc-908a732aeb1c6094c04a7539095352a3349998bc/` there is the commit id 908a732aeb1c6094c04a7539095352a3349998bc which corresponds to v4.0.6. And indeed, v.4.0.6 is not working with valac 0.36. (see this commit https://github.com/pdfpc/pdfpc/commit/d9673035b8ce6863fac23a40397a2b642a4778eb)

**Comment by sanjayankur31** [comment]
Ah, yeh - sorry - PEBKAC :(
