### ISSUE TITLE
Make error with valac 0.28.1 on Ubuntu 16.04.2

### ISSUE THREAD

**Issue by awlayton** [pdfpc/pdfpc#225]
I get the below compilation error when trying to compile with valac 0.28.1, but I can successfully compile with 0.30.1.

It complains about `'fullscreen_on_monitor' does not exist in the context of 'pdfpc.Window.Fullscreen'`. Perhaps the minimum valac version of 0.26 is no longer adequate?

```shellsession
$ cmake ..
-- The C compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Vala: /usr/bin/valac (found suitable version "0.28.1", minimum required is "0.26") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'gobject-2.0'
--   Found gobject-2.0, version 2.48.2
-- Checking for module 'gio-2.0'
--   Found gio-2.0, version 2.48.2
-- Checking for module 'gee-0.8'
--   Found gee-0.8, version 0.18.0
-- Checking for module 'poppler-glib'
--   Found poppler-glib, version 0.48.0
-- Checking for module 'gtk+-3.0>=3.10'
--   Found gtk+-3.0, version 3.18.9
-- Checking for module 'gthread-2.0'
--   Found gthread-2.0, version 2.48.2
-- Checking for module 'pangocairo'
--   Found pangocairo, version 1.38.1
-- Checking for module 'gstreamer-1.0'
--   Found gstreamer-1.0, version 1.8.3
-- Checking for module 'gstreamer-base-1.0'
--   Found gstreamer-base-1.0, version 1.8.3
-- Checking for module 'gstreamer-audio-1.0'
--   Found gstreamer-audio-1.0, version 1.8.3
-- Checking for module 'gstreamer-video-1.0'
--   Found gstreamer-video-1.0, version 1.8.3
-- Checking for module 'gdk-x11-3.0'
--   Found gdk-x11-3.0, version 3.18.9
-- Configuring done
-- Generating done
-- Build files have been written to: /home/awlayton/source/pdfpc/build

$ make -j10
[  3%] Generating pdfpc.c, interfaces/controllable.c, paths.c, classes/options.c, classes/cache_status.c, classes/timer_label.c, classes/window/presentation.c, classes/window/presenter.c, classes/window/overview.c, classes/window/fullscreen.c, classes/action/action_mapping.c, classes/action/movie.c, classes/action/link_action.c, classes/config_file_reader.c, classes/view/pdf.c, classes/view/behaviour/base.c, classes/view/behaviour/pdf_link.c, classes/scaler.c, classes/presentation_controller.c, classes/metadata/slides_notes.c, classes/metadata/pdf.c, classes/renderer/pdf.c, classes/renderer/cache/simple/engine.c, classes/renderer/cache/base.c, classes/renderer/cache/png/engine.c, classes/renderer/cache/png/persistent/engine.c, classes/renderer/cache/png/item.c, classes/dbus_server.c, presenter.vapi, presenter.h, presenter_internal.h
/home/awlayton/source/pdfpc/src/classes/window/fullscreen.vala:159.13-159.38: error: The name `fullscreen_on_monitor' does not exist in the context of `pdfpc.Window.Fullscreen'
            this.fullscreen_on_monitor(this.screen_to_use, this.screen_num_to_use);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/awlayton/source/pdfpc/src/classes/action/movie.vala:553.24-553.43: warning: deprecated syntax, don't use `new' to initialize structs
            var info = new Gst.Video.Info();
                       ^^^^^^^^^^^^^^^^^^^^
Compilation failed: 1 error(s), 1 warning(s)
src/CMakeFiles/pdfpc.dir/build.make:88: recipe for target 'src/pdfpc.c' failed
make[2]: *** [src/pdfpc.c] Error 1
CMakeFiles/Makefile2:86: recipe for target 'src/CMakeFiles/pdfpc.dir/all' failed
make[1]: *** [src/CMakeFiles/pdfpc.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by AndreasBilke** [comment]
We check for gtk version to decide if we use `fullscreen_on_monitor` . Since you have gtk 3.18 you have the API. It seems, that vala 0.28 has not the binding for this gtk API (but vala 0.30 has). Lets see how to fix this.

**Comment by AndreasBilke** [comment]
@awlayton could you check PR #226 ?

**Comment by awlayton** [comment]
Yeah it looks like it talking about the same thing
