### ISSUE TITLE
Linking fails: undefined reference to `gst_video_info_destroy'

### ISSUE THREAD

**Issue by severin-lemaignan** [pdfpc/pdfpc#41]
After bisecting it, this issue has been introduced by 19c26311a9a810b

Exact error:
```
CMakeFiles/pdfpc.dir/classes/action/movie.c.o: In function `pdfpc_controlled_movie_on_prepare':
/home/lemaigna/applis/pdfpc/build/src/classes/action/movie.c:(.text+0x27e8): undefined reference to `gst_video_info_destroy'
```
Note that I'm compiling the project with `clang`.

**Comment by rschroll** [comment]
Hrm.  There's no gst_video_info_destroy in the .c file generated in my build process.  What version of vala are you using?  Which version of gstreamer?

**Comment by severin-lemaignan** [comment]
From CMake output:
```
-- Found Vala: /usr/bin/valac (found suitable version "0.24.0", minimum required is "0.24") 
[...]
-- checking for module 'gstreamer-1.0'
--   found gstreamer-1.0, version 1.2.4
-- checking for module 'gstreamer-base-1.0'
--   found gstreamer-base-1.0, version 1.2.4
-- checking for module 'gstreamer-audio-1.0'
--   found gstreamer-audio-1.0, version 1.2.4
-- checking for module 'gstreamer-video-1.0'
--   found gstreamer-video-1.0, version 1.2.4
[...]
```

`gst_video_info_destroy` appears on line 3466 of my `movie.c` (as generated at commit 19c26311a9a):
```
  3457: #line 488 "/home/lemaigna/applis/pdfpc/src/classes/action/movie.vala"
  3458: tformat = GST_FORMAT_TIME;
  3459: #line 489 "/home/lemaigna/applis/pdfpc/src/classes/action/movie.vala"
  3460: _tmp9_ = overlay;
  3461: #line 489 "/home/lemaigna/applis/pdfpc/src/classes/action/movie.vala"
  3462: gst_element_query_duration (_tmp9_, tformat, &_tmp10_);
  3463: #line 489 "/home/lemaigna/applis/pdfpc/src/classes/action/movie.vala"
  3464: self->duration = _tmp10_;
  3465: #line 480 "/home/lemaigna/applis/pdfpc/src/classes/action/movie.vala"
  3466: gst_video_info_destroy (&info);
  3467: #line 3468 "movie.c"
  3468: }
```

**Comment by rschroll** [comment]
I can reproduce the error with Vala 0.24.

This appears to have been an error in the gstreamer vapi: 
https://bugzilla.gnome.org/show_bug.cgi?id=731895.  We just bumped the 
required Vala up to 0.24; how do people feel about advancing it to 0.26?

**Comment by AndreasBilke** [comment]
Debian Jessie, Ubuntu Vivid and Fedora 21 have all valac 0.26. So we should be okay with this.

**Comment by rschroll** [comment]
@severin-lemaignan: Does Vala 0.26 pose a big problem for you?

**Comment by severin-lemaignan** [comment]
Well, it is not packaged in ubuntu 14.04 LTS. It is not a big deal for me, but it will certainly negatively impact other potential users...

**Comment by rschroll** [comment]
14.04 ships with vala 0.22, so we've already made the decision not to 
support it out of the box.  The only Ubuntu release we're specifically 
disadvantaging by this move would be 14.10, which will reach EOL in 
July, if I'm not mistaken.

Unless I hear any objections soon, I'll go ahead and make the change.  
We may also want to add a reference to the Vala team PPA for 14.04 
users, since that makes it easy to install up-to-date Vala versions.
